name: Typo Check

on:
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y typos hunspell
      - name: Run typo check
        id: typo-check
        run: |
          set -e
          touch tmpfile
          md5sum typos.toml hunspell_whitelist
          typos --words --config=typos.toml | sort -u | hunspell -l -p hunspell_whitelist - > tmpfile
          if [ -s tmpfile ]; then
            echo "Typos found:"
            cat tmpfile
            exit 1
          fi
